-- +goose Up
CREATE TABLE crypto_keystore (
    -- SQLite's INTEGER PRIMARY KEY is a rowid alias, and keyvault.go inserts
    -- without an id and lets it be assigned. Identity reproduces that; BY DEFAULT
    -- rather than ALWAYS so an explicit id still inserts (key recovery/rotation).
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label       TEXT    NOT NULL UNIQUE,   -- 'primary' | 'recovery'
    wrapped_dek BYTEA   NOT NULL,          -- DEK encrypted under this entry's KEK
    kdf         TEXT    NOT NULL,          -- 'argon2id'
    kdf_salt    BYTEA   NOT NULL,          -- 16 random bytes
    kdf_params  TEXT    NOT NULL,          -- JSON: {"m":65536,"t":3,"p":2}
    dek_version INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS crypto_keystore;
